const { existsSync } = require('fs');
const { join } = require('path');
const { config: loadEnv } = require('dotenv');

// ----- Multi-client env loading -----
const APP_LANG = process.env.APP_LANG || 'bn';
const APP_ENV = process.env.APP_ENV || 'development';
const envFile = `.env.${APP_LANG}.${APP_ENV}`;
const envPath = join(__dirname, envFile);

if (existsSync(envPath)) {
  loadEnv({ path: envPath });
} else {
  console.warn(`⚠️  Env file not found: ${envFile}. Using defaults or process.env.`);
}

// ----- Google Services -----
const GOOGLE_SERVICE_FILES = {
  json: 'google-services.json',
  plist: 'GoogleService-Info.plist',
};

const PATHS = {
  googleServicesJson: `./${GOOGLE_SERVICE_FILES.json}`,
  googleServicesPlist: `./${GOOGLE_SERVICE_FILES.plist}`,
  icon: `./assets/images/${APP_LANG}/icon.png`,
  adaptiveIcon: `./assets/images/${APP_LANG}/adaptive-icon.png`,
  splash: `./assets/images/${APP_LANG}/splash-icon.png`,
  favicon: `./assets/images/${APP_LANG}/favicon.png`,
};

const COLORS = {
  primary: '#ffffff',
  splashBackground: '#FFE0B2', // Light saffron - matches theme
};

// ----- Keys for expo extra config -----
const EXTRA_KEYS = {
  language: 'LANGUAGE',
  primaryColor: 'PRIMARY_COLOR',
  bannerAdUnitId: 'BANNER_AD_UNIT_ID',
  interstitialAdUnitId: 'INTERSTITIAL_AD_UNIT_ID',
  rewardedAdUnitId: 'REWARDED_AD_UNIT_ID',
  rewardedInterstitialAdUnitId: 'REWARDED_INTERSTITIAL_AD_UNIT_ID',
  appOpenAdUnitId: 'APP_OPEN_AD_UNIT_ID',
};

// ----- Ad Unit IDs (from env) -----
const AD_UNIT_IDS = {
  banner: process.env.BANNER_AD_UNIT_ID || 'ca-app-pub-3406043589920136/4136707352',
  interstitial: process.env.INTERSTITIAL_AD_UNIT_ID || 'ca-app-pub-3406043589920136/2823625684',
  rewarded: process.env.REWARDED_AD_UNIT_ID || 'ca-app-pub-3406043589920136/5062776214',
  rewardedInterstitial: process.env.REWARDED_INTERSTITIAL_AD_UNIT_ID || 'ca-app-pub-3406043589920136/3167278602',
  appOpen: process.env.APP_OPEN_AD_UNIT_ID || '',
};

// ----- Mobile Ads Config (from env) -----
const MOBILE_ADS_CONFIG = {
  androidAppId: process.env.ADMOB_ANDROID_APP_ID || 'ca-app-pub-3406043589920136~3347511713',
  iosAppId: process.env.ADMOB_IOS_APP_ID || 'ca-app-pub-3940256099942544~1458002511',
};

// ----- App Info (from env) -----
const APP_INFO = {
  name: process.env.APP_NAME || 'গীতা বাংলা',
  slug: process.env.APP_SLUG || 'bhagavad_gita',
  version: '2.0.0',
  package: process.env.APP_PACKAGE || 'com.proninja.bhagavad_gita',
  bundleIdentifier: process.env.APP_BUNDLE_ID || 'com.proninja.bhagavad-gita',
  scheme: 'gita',
};

const fs = require('fs');

// ----- Dynamic Client Asset Bundle -----
// In React Native/Expo, Metro bundles all static `require()` paths.
// To prevent shipping assets (fonts/images) for all 8 languages in a single build,
// we generate a strict type-safe file containing only the `require()` paths for the active client.
function generateActiveClientAssets(lang) {
  const activeAssetsContent = `// AUTO-GENERATED FILE. DO NOT EDIT.
// This file is generated by app.config.js during the build process to ensure Metro 
// only bundles the assets heavily for the active client \`${lang}\`.

export const activeClientFonts = {
  english: require('../../../assets/fonts/${lang}/english.ttf'),
  primary: require('../../../assets/fonts/${lang}/primary.ttf'),
  secondary: require('../../../assets/fonts/${lang}/secondary.ttf'),
};

export const activeClientImages = {
  icon: require('../../../assets/images/${lang}/icon.png'),
  splash: require('../../../assets/images/${lang}/splash-icon.png'),
  adaptiveIcon: require('../../../assets/images/${lang}/adaptive-icon.png'),
  favicon: require('../../../assets/images/${lang}/favicon.png'),
  logo: require('../../../assets/images/${lang}/logo.png'),
};
`;

  const outputPath = join(process.cwd(), 'src/lib/utils/activeClientAssets.ts');
  fs.writeFileSync(outputPath, activeAssetsContent, 'utf-8');
}

module.exports = function ({ config = {} }) {
  const projectRoot = process.cwd();

  // Generate the active client assets BEFORE metro runs
  generateActiveClientAssets(APP_LANG);
  const googleServicesJsonExists = existsSync(join(projectRoot, GOOGLE_SERVICE_FILES.json));
  const googleServicesPlistExists = existsSync(join(projectRoot, GOOGLE_SERVICE_FILES.plist));

  const plugins = [
    'expo-router',
    [
      'expo-build-properties',
      {
        ios: { useFrameworks: 'static' },
        android: { enableMemoryPageSize16K: true },
      },
    ],
    [
      'react-native-google-mobile-ads',
      {
        androidAppId: MOBILE_ADS_CONFIG.androidAppId,
        iosAppId: MOBILE_ADS_CONFIG.iosAppId,
      },
    ],
  ];

  if (googleServicesJsonExists || googleServicesPlistExists) {
    const firebaseConfig = {};
    if (googleServicesJsonExists) {
      firebaseConfig.android = { googleServicesFile: PATHS.googleServicesJson };
    }
    if (googleServicesPlistExists) {
      firebaseConfig.ios = { googleServicesFile: PATHS.googleServicesPlist };
    }
    plugins.push(['@react-native-firebase/app', firebaseConfig]);
  }

  plugins.push('expo-secure-store');

  const androidConfig = {
    package: APP_INFO.package,
    adaptiveIcon: {
      foregroundImage: PATHS.adaptiveIcon,
      backgroundColor: COLORS.primary,
    },
    edgeToEdgeEnabled: true,
    permissions: [
      'android.permission.RECORD_AUDIO',
      'android.permission.MODIFY_AUDIO_SETTINGS',
    ],
    googleServicesFile: PATHS.googleServicesJson,
  };

  const iosConfig = {
    supportsTablet: true,
    bundleIdentifier: APP_INFO.bundleIdentifier,
  };

  if (googleServicesJsonExists) {
    androidConfig.googleServicesFile = PATHS.googleServicesJson;
  }
  if (googleServicesPlistExists) {
    iosConfig.googleServicesFile = PATHS.googleServicesPlist;
  }

  const easProjectId = process.env.EAS_PROJECT_ID;

  const extra = {
    [EXTRA_KEYS.language]: APP_LANG,
    [EXTRA_KEYS.primaryColor]: COLORS.primary,
    eas: { projectId: easProjectId },
    [EXTRA_KEYS.bannerAdUnitId]: AD_UNIT_IDS.banner,
    [EXTRA_KEYS.interstitialAdUnitId]: AD_UNIT_IDS.interstitial,
    [EXTRA_KEYS.rewardedAdUnitId]: AD_UNIT_IDS.rewarded,
    [EXTRA_KEYS.rewardedInterstitialAdUnitId]: AD_UNIT_IDS.rewardedInterstitial,
    [EXTRA_KEYS.appOpenAdUnitId]: AD_UNIT_IDS.appOpen,
    // Supabase (read by services at runtime via Constants)
    SUPABASE_URL: process.env.SUPABASE_URL || 'https://bxcjjqyalflohwjyxdze.supabase.co',
    SUPABASE_ANON_KEY: process.env.SUPABASE_ANON_KEY || '',
    // RevenueCat
    REVENUECAT_ANDROID_API_KEY: process.env.REVENUECAT_ANDROID_API_KEY || '',
    REVENUECAT_IOS_API_KEY: process.env.REVENUECAT_IOS_API_KEY || '',
  };

  return {
    ...config,
    owner: 'proninja',
    name: APP_INFO.name,
    slug: APP_INFO.slug,
    version: APP_INFO.version,
    orientation: 'default',
    icon: PATHS.icon,
    scheme: APP_INFO.scheme,
    splash: {
      image: PATHS.splash,
      resizeMode: 'contain',
      backgroundColor: COLORS.splashBackground,
    },
    userInterfaceStyle: 'automatic',
    newArchEnabled: true,
    runtimeVersion: '1.0.0',
    updates: {
      url: `https://u.expo.dev/${easProjectId}`,
    },
    ios: iosConfig,
    android: androidConfig,
    extra,
    web: {
      output: 'static',
      favicon: PATHS.favicon,
    },
    plugins,
    experiments: {
      typedRoutes: true,
      reactCompiler: true,
    },
  };
};
