import { SIZES } from '@/rootconstants/sizes';
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  backdrop: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  backdropTouchable: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    width: '100%',
    height: '100%',
  },
  blurOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  modalContainer: {
    borderRadius: SIZES.borderRadius.xxl,
    padding: SIZES.spacing.xl,
    alignItems: 'center',
    position: 'relative',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  decorativeBorder: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 4,
    borderTopLeftRadius: SIZES.borderRadius.xxl,
    borderTopRightRadius: SIZES.borderRadius.xxl,
  },
  closeButton: {
    position: 'absolute',
    top: SIZES.spacing.md,
    right: SIZES.spacing.md,
    width: 36,
    height: 36,
    borderRadius: SIZES.borderRadius.full,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 5,
  },
  content: {
    alignItems: 'center',
    paddingTop: SIZES.spacing.lg,
    paddingBottom: SIZES.spacing.md,
    width: '100%',
  },
  iconContainer: {
    width: 100,
    height: 100,
    borderRadius: SIZES.borderRadius.full,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: SIZES.spacing.xl,
    position: 'relative',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 8,
    },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 10,
  },
  iconGlow: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 2,
  },
  iconRing: {
    position: 'absolute',
    width: 120,
    height: 120,
    borderRadius: SIZES.borderRadius.full,
    borderWidth: 2,
    opacity: 0.3,
    top: -10,
    left: -10,
  },
  title: {
    fontSize: SIZES.title,
    fontWeight: 'bold',
    marginBottom: SIZES.spacing.md,
    textAlign: 'center',
    letterSpacing: 0.5,
  },
  message: {
    fontSize: SIZES.lg,
    textAlign: 'center',
    marginBottom: SIZES.spacing.xl,
    lineHeight: SIZES.lg * 1.6,
    paddingHorizontal: SIZES.spacing.md,
    letterSpacing: 0.2,
  },
  proBadgePreview: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: SIZES.spacing.lg,
    paddingVertical: SIZES.spacing.md,
    borderRadius: SIZES.borderRadius.lg,
    marginTop: SIZES.spacing.md,
    borderWidth: 1.5,
    width: '100%',
    justifyContent: 'center',
  },
  badgeIconContainer: {
    marginRight: SIZES.spacing.sm,
  },
  proBadgePreviewText: {
    fontSize: SIZES.md,
    textAlign: 'center',
    flex: 1,
    fontWeight: '600',
  },
});
